# Reference: https://github.com/i3/i3/blob/next/etc/config

config-version = 2

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  'exec-and-forget open -a "Raycast"',
  'exec-and-forget open -a "Tailscale"',
  'exec-and-forget open -a "Ghostty"',
  'exec-and-forget open -a "Google Chrome"',
  'exec-and-forget open -a "Zen"',
  'exec-and-forget open -a "Spark Destkop"',
  'exec-and-forget open -a "Fantastical"',
  'exec-and-forget open -a "Threema"',
  'exec-and-forget open -a "WhatsApp"',
  'exec-and-forget open -a "kChat"',
  'exec-and-forget open -a "kDrive"',
  'exec-and-forget open -a "Synology Drive Client"',
  'exec-and-forget open -a "Dropbox"'
]

# Start AeroSpace at login
start-at-login = false

# In i3, all workspaces are phantom
persistent-workspaces = ["1"]

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
#alt-enter = '''exec-and-forget osascript -e
#    'tell application "Ghostty" to activate' -e
#    'tell application "System Events" to keystroke "n" using {command down}'
#'''
alt-enter = '''exec-and-forget osascript -e '
    tell application "Ghostty"
        activate
    end tell
    tell application "System Events"
        keystroke "n" using {command down}
    end tell'
'''
ctrl-g = '''exec-and-forget osascript -e '
    tell application "Zen"
        make new document at end of documents
        activate
    end tell'
'''

# i3 wraps focus by default
alt-j =         'focus --boundaries-action wrap-around-the-workspace left'
alt-k =         'focus --boundaries-action wrap-around-the-workspace down'
alt-l =         'focus --boundaries-action wrap-around-the-workspace up'
alt-semicolon = 'focus --boundaries-action wrap-around-the-workspace right'

alt-shift-j = 'move left'
alt-shift-k = 'move down'
alt-shift-l = 'move up'
alt-shift-semicolon = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable
# normalizations
alt-h = 'join-with down'
alt-v = 'join-with left'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

ctrl-alt-1 = 'workspace 1'
ctrl-alt-2 = 'workspace 2'
ctrl-alt-3 = 'workspace 3'
ctrl-alt-4 = 'workspace 4'
ctrl-alt-5 = 'workspace 5'
ctrl-alt-6 = 'workspace 6'
ctrl-alt-7 = 'workspace 7'
ctrl-alt-8 = 'workspace 8'
ctrl-alt-9 = 'workspace 9'
ctrl-alt-0 = 'workspace 10'
#ctrl-alt-a = 'workspace A' # In your config, you can drop workspace bindings that you don't need
#ctrl-alt-b = 'workspace B'
#ctrl-alt-c = 'workspace C'
#ctrl-alt-d = 'workspace D'
#ctrl-alt-e = 'workspace E'
#ctrl-alt-f = 'workspace F'
#ctrl-alt-g = 'workspace G'
ctrl-alt-i = 'workspace I'
ctrl-alt-m = 'workspace M'
#ctrl-alt-n = 'workspace N'
#ctrl-alt-o = 'workspace O'
#ctrl-alt-p = 'workspace P'
#ctrl-alt-q = 'workspace Q'
#ctrl-alt-r = 'workspace R'
ctrl-alt-s = 'workspace S'
ctrl-alt-t = 'workspace T'
#ctrl-alt-u = 'workspace U'
#ctrl-alt-v = 'workspace V'
ctrl-alt-w = 'workspace W'
#ctrl-alt-x = 'workspace X'
#ctrl-alt-y = 'workspace Y'
#ctrl-alt-z = 'workspace Z'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
#alt-shift-6 = 'move-node-to-workspace 6'
#alt-shift-7 = 'move-node-to-workspace 7'
#alt-shift-8 = 'move-node-to-workspace 8'
#alt-shift-9 = 'move-node-to-workspace 9'
#alt-shift-0 = 'move-node-to-workspace 10'
alt-shift-i = 'move-node-to-workspace I' # IDE
alt-shift-m = 'move-node-to-workspace M' # Mail
alt-shift-s = 'move-node-to-workspace S' # Social
alt-shift-t = 'move-node-to-workspace T' # Terminal
alt-shift-w = 'move-node-to-workspace W' # Web browser

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
check-further-callbacks = true
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.readdle.SparkDesktop'
run = 'move-node-to-workspace M' # mnemonics M - Mail
[[on-window-detected]]
if.app-id = 'com.flexibits.fantastical2.mac'
run = 'move-node-to-workspace M'

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace I' # mnemonics I - IDE

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace S' # mnemonics S - Social
[[on-window-detected]]
if.app-id = 'ch.threema.threema-desktop'
run = 'move-node-to-workspace S'
[[on-window-detected]]
if.app-id = 'com.infomaniak.chat'
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace T' # mnemonics T - Terminal

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace W'
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = 'move-node-to-workspace W' # mnemonics W - Web browser
